In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.tensor(
    [[1., 2., 3., 4.],
     [5., 6., 7., 8.,],
     [9., 10., 11., 12.]], requires_grad=True
)

w = torch.tensor([[5., 10.],
        [1., 2.]], requires_grad=True)

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [ ]:
x = x.to(device)
w = w.to(device)

In [ ]:
function1 = 10*(x**2).sum()
function2 = torch.log(torch.log(w+7)).prod()

In [ ]:
import requests


In [ ]:
#Считаем градиент
function1.backward()
function2.backward()

In [ ]:
print(x.grad, '<- gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


In [ ]:
print(w.grad, '<-gradient')

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]]) <-gradient


In [ ]:
print(function1.grad_fn)
print(function1.grad_fn.next_functions[0][0])
print(function1.grad_fn.next_functions[0][0].next_functions[0][0])
print(function1.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[0][0])

In [ ]:
#Обновляем значения x, w  . Пишем x.data, так оно позволит обновить значения x и w
alpha = 0.001
x.data -= alpha*x.grad
w.data -= alpha*w.grad

In [ ]:
x.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
w.data

tensor([[ 5.0000, 10.0000],
        [ 1.0000,  2.0000]])

In [ ]:
import torch

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

for _ in range(500):
    # critical: calculate the function inside the loop
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -=  alpha*w.grad# put code here
    w.grad.zero_()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)


In [ ]:
import torch

x = torch.tensor([8., 8.], requires_grad=True)

optimizer = torch.optim.SGD([x], lr=0.001)

def function_parabola(variable):
  return 10*(variable**2).sum()

def make_gradient_step(function, variable):
  function_result = function(variable)
  function_result.backward()
  optimizer.step()
  optimizer.zero_grad()

for i in range(500):
  make_gradient_step(function_parabola, x)

In [ ]:
import torch

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001
optimizer =  torch.optim.SGD([w], lr=alpha)

for _ in range(500):
    # it's critical to calculate function inside the loop:
    function = (w + 7).log().log().prod()
    function.backward()
    optimizer.step()
    optimizer.zero_grad()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)


In [ ]:
import matplotlib.pyplot as plt